### ISSUE TITLE
Decision returned by node-open-policy-agent is different from the one returned by OPA API

### ISSUE THREAD

**Issue by AbirHamzi** [jarden-digital/node-open-policy-agent#1]
**Wished Behavior**
Invoke a nodejs webhook which will return OPA decision using node-open-policy-agent module.

**Actual Behavior**
The result returned by the webhook is different from the one returned by OPA API.

**Steps to Reproduce the Problem**
This katacoda scenario reproduces the problem https://katacoda.com/abir/scenarios/opa-demo .
In the end of scenario you can see that the two results are not the same.

**Comment by jeremy-farnault** [comment]
Hi,

Thanks for that, I'll work on it when I'll get a chance. 

Cheers,
Jeremy
